#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & 10 Buster 64 bit               #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified by Kojex's                           #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# Allah                                         #"
echo -e "# MY FAMILY                                     #"
echo -e "#                                               #"
echo -e "#      AND                                      #"
echo -e "#                                               #"
echo -e "#  PARA PEMBUAT SCRIPY                          #"
echo -e "#          🙏🙏                                #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
